name: Deploy

on:
  push:
    branches:
      - main

  workflow_dispatch:

env:
  IMAGE_URL: ghcr.io/edvardsen-dev/portfolio/sveltekit:latest

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build Docker Image
        run: |
          docker build -t $IMAGE_URL .

      - name: Push Docker Image
        run: |
          docker push $IMAGE_URL

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-publish

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}

      - name: Deploy to VM
        uses: appleboy/ssh-action@v1.1.0
        env:
          GHCR_TOKEN: ${{ secrets.GHCR_TOKEN }}
          GHCR_USER: ${{ github.actor }}
        with:
          host: ${{ secrets.VM_IP }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          envs: GHCR_TOKEN, GHCR_USER, IMAGE_URL, APP_DIR
          script: |
            # Log in to GitHub Container Registry
            echo "${GHCR_TOKEN}" | docker login ghcr.io -u $GHCR_USER --password-stdin

            # Pull the latest image
            docker pull $IMAGE_URL

            # Run new container (Replacing the old one)
            docker run -d -p 3020:3000 --rm --name portfolio_app $IMAGE_URL

            # Clean up old images
            docker image prune -f
